/**
 * Convenience hooks for common Kubernetes operations
 * These are auto-generated wrappers around the generated TanStack Query hooks
 *
 * @generated by common/src/generate-utils.ts
 */
import type { UseQueryOptions } from '@tanstack/react-query';
import {
  useListCoreV1NamespacedPod,
  useListCoreV1Namespace,
  useListCoreV1NamespacedService,
  useListCoreV1Node,
  useListCoreV1NamespacedConfigMap,
  useListCoreV1NamespacedSecret,
} from './generated/core-v1/core-v1';
import {
  useListAppsV1NamespacedDeployment,
  useListAppsV1NamespacedStatefulSet,
  useListAppsV1NamespacedDaemonSet,
} from './generated/apps-v1/apps-v1';
import type {
  IoK8sApiCoreV1PodList,
  IoK8sApiCoreV1NamespaceList,
  IoK8sApiCoreV1ServiceList,
  IoK8sApiCoreV1NodeList,
  IoK8sApiAppsV1DeploymentList,
  IoK8sApiAppsV1StatefulSetList,
  IoK8sApiAppsV1DaemonSetList,
  IoK8sApiCoreV1ConfigMapList,
  IoK8sApiCoreV1SecretList,
} from './generated/models';

/**
 * Common query options for list operations
 */
export interface ListQueryOptions<TData = unknown, TError = unknown> {
  /**
   * Label selector to filter resources
   * @example 'app=nginx,environment=production'
   */
  labelSelector?: string;

  /**
   * Field selector to filter resources
   * @example 'status.phase=Running'
   */
  fieldSelector?: string;

  /**
   * Limit the number of results
   */
  limit?: number;

  /**
   * Continue token for pagination
   */
  continue?: string;

  /**
   * Additional TanStack Query options
   */
  query?: Partial<UseQueryOptions<TData, TError, TData>>;
}

/**
 * List pods in a namespace
 *
 * @example
 * ```typescript
 *  * // List all pods in the default namespace
const { data: pods, isLoading } = usePods('default');
 *
 *  * // List pods with a label selector
const { data: pods } = usePods('default', {
  labelSelector: 'app=nginx',
});
 *
 *  * // With auto-refresh every 5 seconds
const { data: pods } = usePods('default', {
  query: { refetchInterval: 5000 },
});
 * ```
 */
export function usePods(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiCoreV1PodList, void>
) {
  return useListCoreV1NamespacedPod(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List all namespaces
 *
 * @example
 * ```typescript
 *  * const { data: namespaces, isLoading } = useNamespaces();
 *
 *  * // With label selector
const { data: namespaces } = useNamespaces({
  labelSelector: 'environment=production',
});
 * ```
 */
export function useNamespaces(options?: ListQueryOptions<IoK8sApiCoreV1NamespaceList, void>) {
  return useListCoreV1Namespace(
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List services in a namespace
 *
 * @example
 * ```typescript
 *  * const { data: services } = useServices('default');
 *
 *  * // With label selector
const { data: services } = useServices('default', {
  labelSelector: 'app=api',
});
 * ```
 */
export function useServices(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiCoreV1ServiceList, void>
) {
  return useListCoreV1NamespacedService(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List all nodes
 *
 * @example
 * ```typescript
 *  * const { data: nodes } = useNodes();
 *
 *  * // With field selector to get only ready nodes
const { data: readyNodes } = useNodes({
  fieldSelector: 'status.conditions[?(@.type=="Ready")].status=True',
});
 * ```
 */
export function useNodes(options?: ListQueryOptions<IoK8sApiCoreV1NodeList, void>) {
  return useListCoreV1Node(
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List deployments in a namespace
 *
 * @example
 * ```typescript
 *  * const { data: deployments } = useDeployments('default');
 *
 *  * // With label selector
const { data: deployments } = useDeployments('default', {
  labelSelector: 'app=frontend',
});
 * ```
 */
export function useDeployments(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiAppsV1DeploymentList, void>
) {
  return useListAppsV1NamespacedDeployment(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List StatefulSets in a namespace
 *
 * @example
 * ```typescript
 *  * const { data: statefulSets } = useStatefulSets('default');
 * ```
 */
export function useStatefulSets(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiAppsV1StatefulSetList, void>
) {
  return useListAppsV1NamespacedStatefulSet(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List DaemonSets in a namespace
 *
 * @example
 * ```typescript
 *  * const { data: daemonSets } = useDaemonSets('kube-system');
 * ```
 */
export function useDaemonSets(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiAppsV1DaemonSetList, void>
) {
  return useListAppsV1NamespacedDaemonSet(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List ConfigMaps in a namespace
 *
 * @example
 * ```typescript
 *  * const { data: configMaps } = useConfigMaps('default');
 * ```
 */
export function useConfigMaps(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiCoreV1ConfigMapList, void>
) {
  return useListCoreV1NamespacedConfigMap(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}

/**
 * List Secrets in a namespace
 *
 * @example
 * ```typescript
 *  * const { data: secrets } = useSecrets('default');
 *
 *  * // Filter by type
const { data: tlsSecrets } = useSecrets('default', {
  fieldSelector: 'type=kubernetes.io/tls',
});
 * ```
 */
export function useSecrets(
  namespace: string,
  options?: ListQueryOptions<IoK8sApiCoreV1SecretList, void>
) {
  return useListCoreV1NamespacedSecret(
    namespace,
    {
      labelSelector: options?.labelSelector,
      fieldSelector: options?.fieldSelector,
      limit: options?.limit,
      continue: options?.continue,
    },
    { query: options?.query }
  );
}
